FROM python:3.12-slim

WORKDIR /app

COPY python/ .

RUN pip install --no-cache-dir \
    streamlit \
    pandas \
    plotly \
    sqlalchemy \
    psycopg2-binary

EXPOSE 8501

CMD ["streamlit", "run", "dashboard.py", "--server.address=0.0.0.0", "--server.port=8501"]